name: Linux Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repo
      uses: actions/checkout@v5
    - name: Install openblas and lapack
      run: sudo apt-get install libopenblas-dev liblapacke-dev
    - name: Find dependency paths
      id: dependencies
      run: |
        OPENBLAS_LIB=$(dpkg -L libopenblas-pthread-dev | grep ^\/.*\/libopenblas.a$ | head -n1)
        OPENBLAS_INC=$(dpkg -L libopenblas-pthread-dev | grep ^\/.*\/cblas.h$ | head -n1 | sed 's:[^/]*$::')
        LAPACK_LIB=$(dpkg -L libopenblas-pthread-dev | grep ^\/.*\/liblapack.a$ | head -n1)
        LAPACKE_LIB=$(dpkg -L liblapacke-dev | grep ^\/.*\/liblapacke.a$ | head -n1)
        LAPACKE_INC=$(dpkg -L liblapacke-dev | grep ^\/.*\/lapacke.h$ | head -n1 | sed 's:[^/]*$::')
        echo "openblas-lib=$OPENBLAS_LIB$" >> "$GITHUB_OUTPUT"
        echo "openblas-inc=$OPENBLAS_INC$" >> "$GITHUB_OUTPUT"
        echo "lapack-lib=$LAPACK_LIB$" >> "$GITHUB_OUTPUT"
        echo "lapacke-lib=$LAPACKE_LIB$" >> "$GITHUB_OUTPUT"
        echo "lapacke-inc=$LAPACKE_INC$" >> "$GITHUB_OUTPUT"
    - name: install-deps
      run: cd install-deps; ./mkdeps.sh --build-superlu=yes; cd ..
    - name: make
      run: make CC=clang -j LAPACK_INC="${{ steps.dependencies.openblas-inc }} ${{ steps.dependencies.lapacke-inc }}" LAPACK_LIB="${{ steps.dependencies.openblas-lib }} ${{ steps.dependencies.lapack-lib }} ${{ steps.dependencies.lapacke-lib }}"
    - name: make check
      run: make CC=clang check -j LAPACK_INC="${{ steps.dependencies.openblas-inc }} ${{ steps.dependencies.lapacke-inc }}" LAPACK_LIB="${{ steps.dependencies.openblas-lib }} ${{ steps.dependencies.lapack-lib }} ${{ steps.dependencies.lapacke-lib }}"
    - name: make regression
      run: make -j regression
