name: Linux Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repo
      uses: actions/checkout@v5
    - name: Install openblas and lapack
      run: sudo apt-get install libopenblas-dev liblapacke-dev
    - name: Find dependency paths
      id: dependencies
      run: |
        LAPACK_LIB=$(dpkg -L liblapacke-dev | grep ^\/.*\/liblapacke.a$ | head -n1)
        LAPACK_INC=$(dpkg -L liblapacke-dev | grep ^\/.*\/lapacke.h$ | head -n1 | sed 's:[^/]*$::') 
    - name: install-deps
      run: cd install-deps; ./mkdeps.sh --build-superlu=yes; cd ..
    - name: make
      run: make CC=clang -j
    - name: make check
      run: make CC=clang check -j
    - name: make regression
      run: make -j regression
