name: Mac Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build:
    if: github.event.pull_request.draft == false
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v5
    - name: install-superlu
      run: cd install-deps; ./mkdeps.sh  --build-superlu=yes; cd ..    
    - name: make
      run: make -j
    - name: make regression
      run: make -j regression
    - name: make check
      run: make -j check
